version: '3.8'

x-app-service: &default-app
  build: .
  command: ''
  container_name: ''
  environment:
    - MONGO_URL=mongodb://mongo:27017/trials-backend-dev
  networks:
    - trials-network
  volumes:
    - .:/code
    - node_modules:/code/node_modules

services:
  trials-backend:
    <<: *default-app
    container_name: 'app'
    command: bash -c "npm run build && npm run start:trials:backend"
    environment:
      - PORT=5000
    ports:
      - '5000:5000'
    user: 'root'

  mongo:
    container_name: 'mongo'
    image: mongo:3.6.0
    networks:
      - trials-network
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  node_modules:
  mongo_data:

networks:
  trials-network:
