imports:
  - { resource: ./application.yaml }

services:
  Shared.EnvironmentArranger:
    class: ../../../tests/shared/mongoose/MongooseEnvironmentArranger
    arguments: ['@Shared.ConnectionManager']
